import 'package:flutter/material.dart';
import '../models/assignment_model.dart';
import '../models/student_data_model.dart';
import '../services/assignment_service.dart';
import '../services/student_service.dart';

class CreateAssignmentScreen extends StatefulWidget {
  final String teacherId;
  final String teacherName;

  const CreateAssignmentScreen({
    Key? key,
    required this.teacherId,
    required this.teacherName,
  }) : super(key: key);

  @override
  _CreateAssignmentScreenState createState() => _CreateAssignmentScreenState();
}

class _CreateAssignmentScreenState extends State<CreateAssignmentScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _dueDateController = TextEditingController();
  DateTime? _dueDate;
  final List<String> _selectedStudentIds = [];
  final List<String> _selectedStudentNames = [];
  final AssignmentService _assignmentService = AssignmentService();
  final StudentService _studentService = StudentService();
  List<StudentData> _allStudents = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadStudents();
  }

  Future<void> _loadStudents() async {
    setState(() => _isLoading = true);
    try {
      _allStudents = await _studentService.getAllStudents();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('فشل في تحميل قائمة الطلاب: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  Future<void> _selectDueDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now().add(const Duration(days: 7)),
      firstDate: DateTime.now(),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      setState(() {
        _dueDate = picked;
        _dueDateController.text = '${picked.year}-${picked.month}-${picked.day}';
      });
    }
  }

  void _toggleStudentSelection(StudentData student) {
    setState(() {
      if (_selectedStudentIds.contains(student.id)) {
        _selectedStudentIds.remove(student.id);
        _selectedStudentNames.remove(student.name);
      } else {
        _selectedStudentIds.add(student.id);
        _selectedStudentNames.add(student.name);
      }
    });
  }

  Future<void> _submitAssignment() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedStudentIds.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('الرجاء اختيار طالب واحد على الأقل')),
      );
      return;
    }

    try {
      final assignment = CustomAssignment(
        id: '', // Will be generated by the service
        teacherId: widget.teacherId,
        teacherName: widget.teacherName,
        assignedStudentIds: _selectedStudentIds,
        assignedStudentNames: _selectedStudentNames,
        questions: [], // Add questions here if needed
        title: _titleController.text,
        description: _descriptionController.text.isNotEmpty ? _descriptionController.text : null,
        dueDate: _dueDate,
        isActive: true,
      );

      await _assignmentService.saveAssignment(assignment);
      
      if (mounted) {
        Navigator.pop(context, true); // Return success
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('تم إرسال الواجب بنجاح')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('فشل في حفظ الواجب: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('إنشاء واجب جديد'),
        centerTitle: true,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    TextFormField(
                      controller: _titleController,
                      decoration: const InputDecoration(
                        labelText: 'عنوان الواجب',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) =>
                          value?.isEmpty ?? true ? 'الرجاء إدخال عنوان للواجب' : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _descriptionController,
                      maxLines: 3,
                      decoration: const InputDecoration(
                        labelText: 'وصف الواجب (اختياري)',
                        border: OutlineInputBorder(),
                        alignLabelWithHint: true,
                      ),
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _dueDateController,
                      readOnly: true,
                      onTap: _selectDueDate,
                      decoration: const InputDecoration(
                        labelText: 'تاريخ الاستحقاق',
                        border: OutlineInputBorder(),
                        suffixIcon: Icon(Icons.calendar_today),
                      ),
                      validator: (value) =>
                          _dueDate == null ? 'الرجاء اختيار تاريخ الاستحقاق' : null,
                    ),
                    const SizedBox(height: 24),
                    const Text(
                      'اختر الطلاب:',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Container(
                      height: 200,
                      decoration: BoxDecoration(
                        border: Border.all(color: Colors.grey),
                        borderRadius: BorderRadius.circular(4),
                      ),
                      child: _allStudents.isEmpty
                          ? const Center(child: Text('لا يوجد طلاب مسجلين'))
                          : ListView.builder(
                              itemCount: _allStudents.length,
                              itemBuilder: (context, index) {
                                final student = _allStudents[index];
                                return CheckboxListTile(
                                  title: Text(student.name),
                                  value: _selectedStudentIds.contains(student.id),
                                  onChanged: (_) => _toggleStudentSelection(student),
                                );
                              },
                            ),
                    ),
                    const SizedBox(height: 32),
                    ElevatedButton(
                      onPressed: _submitAssignment,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                      ),
                      child: const Text(
                        'حفظ وإرسال الواجب',
                        style: TextStyle(fontSize: 16),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _dueDateController.dispose();
    super.dispose();
  }
}
